version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 10
    assignees:
      - pmmmwh
    labels:
      - dependencies
    groups:
      eslint:
        patterns:
          - "@eslint/*"
          - eslint
    versioning-strategy: widen
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 10
    assignees:
      - pmmmwh
    labels:
      - dependencies
