name: Detect Dependabot

on:
  push:
    branches:
      - dependabot/npm_and_yarn/**

jobs:
  detect-dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - run: echo "Branch updated by Dependabot"
